### PR TITLE
instrument: support middleware as selector expression

### LINKED ISSUE #51: [BUG] panic: ast.Walk when I try to instrument.
**Version of orchestrion**

**v0.4.1**

**Describe what happened:**
I would like to instrument a project that I regularly use. But I've a panic. 
```
panic: ast.Walk: unexpected node type <nil>

goroutine 1 [running]:
github.com/dave/dst.Walk({0x727d38?, 0xc0005a7800?}, {0x0?, 0x0?})
        /home/bagl3y/go/pkg/mod/github.com/dave/dst@v0.27.2/walk.go:332 +0x1894
github.com/dave/dst.walkStmtList(...)
        /home/bagl3y/go/pkg/mod/github.com/dave/dst@v0.27.2/walk.go:32
github.com/dave/dst.Walk({0x727d38?, 0xc0005a7800?}, {0x727ed8?, 0xc00017be00?})
        /home/bagl3y/go/pkg/mod/github.com/dave/dst@v0.27.2/walk.go:216 +0x1ca5
github.com/dave/dst.Walk({0x727d38?, 0xc0005a7800?}, {0x728398?, 0xc0001103c0?})
        /home/bagl3y/go/pkg/mod/github.com/dave/dst@v0.27.2/walk.go:315 +0x1725
github.com/dave/dst.walkDeclList(...)
        /home/bagl3y/go/pkg/mod/github.com/dave/dst@v0.27.2/walk.go:38
github.com/dave/dst.Walk({0x727d38?, 0xc0005a7800?}, {0x7283b8?, 0xc0000f0410?})
        /home/bagl3y/go/pkg/mod/github.com/dave/dst@v0.27.2/walk.go:321 +0x18e5
github.com/dave/dst.Inspect(...)
        /home/bagl3y/go/pkg/mod/github.com/dave/dst@v0.27.2/walk.go:353
github.com/dave/dst/decorator.(*FileRestorer).updateImports(0xc00045c2d0)
        /home/bagl3y/go/pkg/mod/github.com/dave/dst@v0.27.2/decorator/restorer.go:190 +0x176
github.com/dave/dst/decorator.(*FileRestorer).RestoreFile(0xc00045c2d0, 0x0?)
        /home/bagl3y/go/pkg/mod/github.com/dave/dst@v0.27.2/decorator/restorer.go:135 +0x23e
github.com/dave/dst/decorator.(*Restorer).RestoreFile(...)
        /home/bagl3y/go/pkg/mod/github.com/dave/dst@v0.27.2/decorator/restorer.go:65
github.com/dave/dst/decorator.(*Restorer).Fprint(0xc0005a8480, {0x727c58, 0xc000003890}, 0x6c18c0?)
        /home/bagl3y/go/pkg/mod/github.com/dave/dst@v0.27.2/decorator/restorer.go:56 +0x93
github.com/datadog/orchestrion/internal/instrument.InstrumentFile({0xc000164828, 0x16}, {0x727ab8?, 0xc000324788}, {{0x6c8f9b?, 0xc000164828?}})
        /home/bagl3y/go/pkg/mod/github.com/datadog/orchestrion@v0.4.1/internal/instrument/instrument.go:103 +0x777
github.com/datadog/orchestrion/internal/instrument.ProcessPackage.func1({0xc000164828, 0x16}, {0x72af90?, 0xc0001b3440?}, {0x0?, 0x0?})
        /home/bagl3y/go/pkg/mod/github.com/datadog/orchestrion@v0.4.1/internal/instrument/instrument.go:48 +0x20c
io/fs.walkDir({0x727bb8, 0xc0000421a0}, {0xc000164828, 0x16}, {0x72af90, 0xc0001b3440}, 0xc0004fbdc8)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.21.3/libexec/src/io/fs/walk.go:73 +0x6c
io/fs.walkDir({0x727bb8, 0xc0000421a0}, {0xc000128d10, 0xf}, {0x72af90, 0xc0001b3180}, 0xc0004fbdc8)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.21.3/libexec/src/io/fs/walk.go:95 +0x2c5
io/fs.walkDir({0x727bb8, 0xc0000421a0}, {0xc000128ca0, 0xb}, {0x72af90, 0xc0001bd0c0}, 0xc0004fbdc8)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.21.3/libexec/src/io/fs/walk.go:95 +0x2c5
io/fs.walkDir({0x727bb8, 0xc0000421a0}, {0xc00026fb10, 0x3}, {0x72af90, 0xc0000c66c0}, 0xc0004fbdc8)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.21.3/libexec/src/io/fs/walk.go:95 +0x2c5
io/fs.walkDir({0x727bb8, 0xc0000421a0}, {0x726af4, 0x1}, {0x72afc8, 0xc0000421b0}, 0xc0004fbdc8)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.21.3/libexec/src/io/fs/walk.go:95 +0x2c5
io/fs.WalkDir({0x727bb8, 0xc0000421a0}, {0x726af4, 0x1}, 0xc000185dc8)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.21.3/libexec/src/io/fs/walk.go:122 +0xd2
github.com/datadog/orchestrion/internal/instrument.ProcessPackage({0xc0000305c0, 0x32}, 0x6dd7d8, 0x6dd7f8, {{0x6c8f9b?, 0x1?}})
        /home/bagl3y/go/pkg/mod/github.com/datadog/orchestrion@v0.4.1/internal/instrument/instrument.go:36 +0xd6
main.main()
        /home/bagl3y/go/pkg/mod/github.com/datadog/orchestrion@v0.4.1/main.go:77 +0x4e9
```
**Describe what you expected:**
Instrument my project

**Steps to reproduce the issue:**
Clone https://github.com/gotenberg/gotenberg and try to instrument it (`orchestrion -w ./`)

**Additional environment details (Version of Go, Operating System, etc.):**

Golang 1.21.3 linux/amd64 (Same issue in a Docker Build)

### PR DESCRIPTION
**Pull request by ahmed-mez**
### What does this PR do?

Add support for using middlewares when the server is a struct field. Before this fix, Orchestrion would inject a nil statement which causes a panic in `ast.Walk`.

### Motivation

fixes #51 

This commit has also been tested against https://github.com/gotenberg/gotenberg as mentioned in the issue.

### Reviewer's Checklist

- [x] Changed code has unit tests for its functionality.

### CODE REVIEW

File: internal/instrument/instrument.go [hunk 1]
```diff
@@ -571,24 +572,85 @@ func funcIdent(e dst.Expr) (*dst.Ident, bool) {
...
+		//dd:instrumented
+		r := echo.New()
+		//dd:startinstrument
+		r.Use(instrument.EchoV4Middleware())
+		//dd:endinstrument
+
+		//dd:instrumented
+		api.server = echo.New()
+		//dd:startinstrument
+		api.serverr.Use(instrument.EchoV4Middleware())
```
Comment (darccio) [inline internal/instrument/instrument.go:587]:
```suggestion
		api.server.Use(instrument.EchoV4Middleware())
```

File: internal/instrument/instrument.go [hunk 2]
```diff
@@ -571,24 +572,85 @@ func funcIdent(e dst.Expr) (*dst.Ident, bool) {
...
+						Sel: &dst.Ident{Name: ex.Sel.Name},
+					},
+					Sel: &dst.Ident{Name: "Use"},
+				},
+				Args: []dst.Expr{
+					&dst.CallExpr{
+						Fun: &dst.Ident{
+							Name: middleware,
+							Path: "github.com/datadog/orchestrion/instrument",
+						},
```
Comment (darccio) [inline internal/instrument/instrument.go:628]: I think we can avoid the duplication by checking first what type of expression we have. Then, in case of a `SelectorExpr`, assign the underlying `Ident`. If not, assign the received expression, always if it's a Ident. From the found expression we can deduce if we need to a `X.Fun.X` `SelectorExpr` equal to `dst.Ident{Name: ex.Name}` or `dst.SelectorExpr{X: dst.Ident{Name: x.Name}, Sel: dst.Ident{Name: ex.Sel.Name}}`.

WDYT, @ahmed-mez?

File: internal/instrument/echov4.go [hunk 3]
```diff
@@ -8,14 +8,7 @@ package instrument
...
 func instrumentEchoV4(stmt *dst.AssignStmt) []dst.Stmt {
-	if !isEchoV4(stmt) {
-		return nil
-	}
-	stmt.Decorations().Start.Prepend(dd_instrumented)
-	return []dst.Stmt{
-		stmt,
-		echoV4Middleware(stmt),
-	}
+	return instrumentMiddleware(stmt, isEchoV4, "EchoV4Middleware")
```
Comment (darccio) [inline internal/instrument/echov4.go:11]: Nice to see this refactor.

**Review by darccio — CHANGES_REQUESTED** [review]

File: internal/instrument/instrument.go (hunk 2 above)
Comment (ahmed-mez) [reply internal/instrument/instrument.go:628]: I considered that, but kept the two cases seperated tin the end to ease readability. I agree that we could avoid some duplication but the code would be much harder to read. At least right now the separation between the 2 cases is obvious and the reader would just need to focus on one branch.

It's not a strong opinion though, happy to reconsider. Mind sharing a code suggestion for what you described?

Comment (darccio) [reply internal/instrument/instrument.go:628]: @ahmed-mez My suggestion would look like this:

```go
// useMiddleware returns a statement that uses the given middleware.
func useMiddleware(expr dst.Expr, middleware string) (*dst.ExprStmt, error) {
	/*
		//dd:instrumented
		r := echo.New()
		//dd:startinstrument
		r.Use(instrument.EchoV4Middleware())
		//dd:endinstrument

		//dd:instrumented
		api.server = echo.New()
		//dd:startinstrument
		api.server.Use(instrument.EchoV4Middleware())
		//dd:endinstrument
	*/
	var rExpr dst.Expr
	switch ex := expr.(type) {
	case *dst.Ident:
		rExpr = &dst.Ident{Name: ex.Name}
	case *dst.SelectorExpr:
		x, ok := ex.X.(*dst.Ident)
		if !ok {
			return nil, fmt.Errorf("unexpected type %v", reflect.TypeOf(ex.X))
		}
		rExpr = &dst.SelectorExpr{
			X:   &dst.Ident{Name: x.Name},
			Sel: &dst.Ident{Name: ex.Sel.Name},
		}
	default:
		return nil, fmt.Errorf("unexpected type %v", reflect.TypeOf(expr))
	}
	stmt := &dst.ExprStmt{
		X: &dst.CallExpr{
			Fun: &dst.SelectorExpr{
				X:   rExpr,
				Sel: &dst.Ident{Name: "Use"},
			},
			Args: []dst.Expr{
				&dst.CallExpr{
					Fun: &dst.Ident{
						Name: middleware,
						Path: "github.com/datadog/orchestrion/instrument",
					},
				},
			},
		},
	}
	markAsInstrumented(stmt)
	return stmt, nil
}
``` 

Tests pass for me locally with this change.

Comment (ahmed-mez) [reply internal/instrument/instrument.go]: Thanks, applied the suggestion!

**Review by darccio — APPROVED** [review]
