### PR TITLE
fix(injector): nil-dereference on a specific import order

### LINKED ISSUE #272: [BUG] While instrumenting the rclone repo I got a SIGSEGV
**Version of orchestrion**
master

**Describe what happened:**
I'm working on the CI Visibility instrumentation and while testing with the `rclone` repo I hit the following panic in orchestrion:

```go
...
ok  	github.com/rclone/rclone/lib/kv	0.775s
ok  	github.com/rclone/rclone/lib/mmap	0.992s
ok  	github.com/rclone/rclone/lib/pacer	2.020s
# github.com/rclone/rclone/librclone
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x1015e059c]

goroutine 1 [running]:
github.com/datadog/orchestrion/internal/injector.filterExtraneousImports(...)
	../../tonyredondo/orchestrion/internal/injector/imports.go:56
github.com/datadog/orchestrion/internal/injector.canonicalizeImports(0x14000276a90)
	../../tonyredondo/orchestrion/internal/injector/imports.go:25 +0x21c
github.com/datadog/orchestrion/internal/injector.(*Injector).writeModifiedFile(0x1400017ea80, 0x140001df7a0, 0x14000276a90)
	../../tonyredondo/orchestrion/internal/injector/write.go:23 +0x34
github.com/datadog/orchestrion/internal/injector.(*Injector).injectFile(0x1400017ea80, 0x140001df7a0, 0x14000276a90)
	../../tonyredondo/orchestrion/internal/injector/injector.go:132 +0xa4
github.com/datadog/orchestrion/internal/injector.(*Injector).InjectFiles(0x1400017ea80, {0x1400031cdc0, 0x3, 0x15})
	../../tonyredondo/orchestrion/internal/injector/injector.go:98 +0x33c
github.com/datadog/orchestrion/internal/toolexec/aspect.Weaver.OnCompile({{0x1400003a214?, 0x100cec920?}}, 0x1400030a300)
	../../tonyredondo/orchestrion/internal/toolexec/aspect/oncompile.go:82 +0x684
github.com/datadog/orchestrion/internal/toolexec/proxy.ProcessCommand[...]({0x1019b3b18?, 0x1400030a300?}, 0x14000229708?)
	../../tonyredondo/orchestrion/internal/toolexec/proxy/proxy.go:74 +0x44
github.com/datadog/orchestrion/internal/cmd.init.func4(0x14000229978?)
	../../tonyredondo/orchestrion/internal/cmd/toolexec.go:56 +0x2ac
github.com/urfave/cli/v2.(*Command).Run(0x102004c20, 0x140001314c0, {0x1400031c580, 0x16, 0x16})
	../../../../go/pkg/mod/github.com/urfave/cli/v2@v2.27.4/command.go:276 +0x600
github.com/urfave/cli/v2.(*Command).Run(0x1400031c160, 0x14000131280, {0x140001c2000, 0x17, 0x18})
	../../../../go/pkg/mod/github.com/urfave/cli/v2@v2.27.4/command.go:269 +0x83c
github.com/urfave/cli/v2.(*App).RunContext(0x1400017c600, {0x1019b0e40, 0x1020c5c60}, {0x140001c2000, 0x17, 0x18})
	../../../../go/pkg/mod/github.com/urfave/cli/v2@v2.27.4/app.go:333 +0x51c
github.com/urfave/cli/v2.(*App).Run(...)
	../../../../go/pkg/mod/github.com/urfave/cli/v2@v2.27.4/app.go:307
main.main()
	../../tonyredondo/orchestrion/main.go:162 +0x71c
ok  	github.com/rclone/rclone/lib/pool	2.385s
ok  	github.com/rclone/rclone/lib/random	0.745s
ok  	github.com/rclone/rclone/lib/ranges	0.885s
...
```

**Describe what you expected:**
not to panic

**Steps to reproduce the issue:**

Just ran `/Users/tony.redondo/repos/github/tonyredondo/orchestrion/orchestrion go test ./...` 

**Additional environment details (Version of Go, Operating System, etc.):**

```bash
❯ go version
go version go1.23.0 darwin/arm64
```

```bash
❯ sw_vers
ProductName:		macOS
ProductVersion:		14.6.1
BuildVersion:		23G93
```

### PR DESCRIPTION
**Pull request by eliottness**
- [x] Add tests for the import filtering
- [x] Fixes #272 
- [x] Fix potential data-race because golangci-lint was complaining

### CODE REVIEW

File: internal/injector/injector.go [hunk 1]
```diff
@@ -96,7 +96,7 @@ func (i *Injector) InjectFiles(files []string) (map[string]InjectedFile, error)
 
 	wg.Add(len(astFiles))
 	for idx, astFile := range astFiles {
-		go func(astFile *ast.File) {
+		go func(idx int, astFile *ast.File) {
```
Comment (RomainMuller) [inline internal/injector/injector.go:99]: Nice

File: internal/injector/write.go [hunk 2]
```diff
@@ -13,13 +13,15 @@ import (
...
 	"github.com/dave/dst/decorator"
 )
 
 // writeModifiedFile writes the modified file to disk after having restored it to Go source code,
 // and returns the path to the modified file.
 func (i *Injector) writeModifiedFile(decorator *decorator.Decorator, file *dst.File) (string, error) {
+	log.Tracef("writing modified file %q\n", decorator.Filenames[file])
 	canonicalizeImports(file)
 
 	filename := decorator.Filenames[file]
```
Comment (RomainMuller) [inline internal/injector/write.go:27]:
```suggestion
	filename := decorator.Filenames[file]
	log.Tracef("writing modified file %q\n", filename)

	canonicalizeImports(file)
```

**Review by RomainMuller — APPROVED** [review]

**Review by tonyredondo — APPROVED** [review]
