### PR TITLE
fix: required-version respawning of orchestrion causes build failures

### LINKED ISSUE #507: [BUG] builds fail with `sending never-build-twice request: mismatched build ID for ...`
> [!IMPORTANT]
> **Maintainer note:**
> If you are encountering this issue, and use `orchestrion` by specifying the `-toolexec='orchestrion toolexec'` argument to `go` (either via command line arguments, or through `GOFLAGS`), the issue is likely caused by:
> 1. You have installed some version of `orchestrion` (`go install github.com/DataDog/orchestrion@<some-version>`)
> 2. Your `go.mod` file lists _another_ version of `orchestrion`
> 
> In this case, making sure both versions are identical should fix the issue (if not, please tell us in this issue!).
>
> If you are facing the same problem, but your situation does not match the above description, please let us know by filing a separate issue.

**Version of orchestrion**
1.0.3

**Describe what happened:**
Since today, I cannot build some of our micro-services with orchestrion. Here is an extract of logs I get in the `go build`command:

```
#16 89.36 sending never-build-twice request: mismatched build ID for "sync/atomic": "3A1CLLn9Q6jnXEL4WfTC/3A1CLLn9Q6jnXEL4WfTC" != "PxIKMSNesE1tGk6jxW68/PxIKMSNesE1tGk6jxW68"
#16 89.36 -: # internal/godebugs
#16 89.36 sending never-build-twice request: mismatched build ID for "internal/godebugs": "4gNYbdB7k-Lxicu-bDPb/4gNYbdB7k-Lxicu-bDPb" != "3iGATNQByhC2W3eE5YoK/3iGATNQByhC2W3eE5YoK"
#16 89.36 -: # internal/race
#16 89.36 sending never-build-twice request: mismatched build ID for "internal/race": "ntwMDWhcLGfGB-u85-hr/ntwMDWhcLGfGB-u85-hr" != "Cs-OKq4eFdzAa-H6E2Sr/Cs-OKq4eFdzAa-H6E2Sr"
#16 89.36 -: # internal/goexperiment
#16 89.36 sending never-build-twice request: mismatched build ID for "internal/goexperiment": "bcDhOEOGMfS059ucNwlc/bcDhOEOGMfS059ucNwlc" != "DX1Zfyf9VWPnJnMlVYmN/DX1Zfyf9VWPnJnMlVYmN"
#16 89.36 -: # internal/goos
#16 89.36 sending never-build-twice request: mismatched build ID for "internal/goos": "zRhU4mh_wktcsl0M_szK/zRhU4mh_wktcsl0M_szK" != "fbhkRpj4jP_3rgmYeY1W/fbhkRpj4jP_3rgmYeY1W"
#16 89.36 -: # internal/cpu
#16 89.36 sending never-build-twice request: mismatched build ID for "internal/cpu": "BBZvZV26hr-0JI6Lo1PT/BBZvZV26hr-0JI6Lo1PT" != "x1SG1wxC4tQEQhm1cs7F/x1SG1wxC4tQEQhm1cs7F"
#16 89.36 -: # internal/goarch
#16 89.36 sending never-build-twice request: mismatched build ID for "internal/goarch": "gwQ89hWjJOOIkI6ho_gc/gwQ89hWjJOOIkI6ho_gc" != "g9PlaGbp4lE0n0WKGnZT/g9PlaGbp4lE0n0WKGnZT"
#16 89.36 -: # internal/cpu
#16 89.36 sending never-build-twice request: mismatched build ID for "internal/cpu": "BBZvZV26hr-0JI6Lo1PT/BBZvZV26hr-0JI6Lo1PT" != "x1SG1wxC4tQEQhm1cs7F/x1SG1wxC4tQEQhm1cs7F"
#16 89.36 -: # internal/runtime/atomic
#16 89.36 sending never-build-twice request: mismatched build ID for "internal/runtime/atomic": "zwhihA7OyTql8MynRG1k/zwhihA7OyTql8MynRG1k" != "tihqsHspYa5l3KybMTIU/tihqsHspYa5l3KybMTIU"
#16 89.36 -: # internal/byteorder

```

**Describe what you expected:**
Build success

**Steps to reproduce the issue:**
I don't have at hand a minimum reproducible example, sorry. But I know that it works for v1.0.2, it seems to be a regression with v1.0.3.

I can share though my build command and `go.mod` extract:

```bash
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -toolexec=\"orchestrion toolexec\"     -ldflags='-w -s -extldflags \"-static\"' -a -o /bin/foo .
```

main `go.mod`

```
module foo

go 1.23

replace foo/common => ../common

require (
	foo/common v0.0.0-00010101000000-000000000000
	github.com/DataDog/orchestrion v1.0.2
	github.com/gorilla/mux v1.8.1
	github.com/gorilla/schema v1.4.1
	github.com/jinzhu/gorm v1.9.16
)
```

common `go.mod`:

```
module foo/common

go 1.23
```

**Additional environment details (Version of Go, Operating System, etc.):**
Compiling in amd64, inside an official golang 1.23.5 Debian bookworm based docker image.

### PR DESCRIPTION
**Pull request by RomainMuller**
The automatic version check incurring a re-spawn of orchestrion with the `go.mod` version cannot happen in all situations, and this results in inconsistent build IDs being generated when manually specifying `-toolexec` (instead of using `orchestrion go ...`).

Since we cannot always do the version check, we cannot re-spawn in all situations. For now, we decided to no longer re-spawn but instead produce specific error messages when the running version is not the one required by `go.mod`, instructing users what to do to fix that.

Fixes #507

### CODE REVIEW

File: internal/pin/auto.go [hunk 1]
```diff
@@ -21,60 +23,64 @@ import (
...
+			log.Trace().Err(err).Msg("Orchestrion is already in go.mod, but we are not running the correct one; returning an error")
+			return err
+		} else if err == nil {
 			// We're good to go
-			return
+			log.Trace().Msg("Orchestrion is already in go.mod, and we are running the correct version, no automatic pinning required")
+			return nil
 		}
+		log.Trace().Err(err).Msg("Failed to detect required version of orchestrion from go.mod")
 	} else {
```
Comment (eliottness) [inline internal/pin/auto.go:54]: Same here since all cases in the `if` return

File: internal/pin/auto.go [hunk 2]
```diff
@@ -21,60 +23,64 @@ import (
...
 		log.Trace().Msg("Skipping ensure.RequiredVersion because this is a development build")
 		_, err := os.Stat(config.FilenameOrchestrionToolGo)
 		if err == nil {
 			log.Trace().Msg("Found " + config.FilenameOrchestrionToolGo + " file, no automatic pinning required")
-			return
+			return nil
+		} else if !errors.Is(err, os.ErrNotExist) {
+			log.Trace().Msg("Failed to stat " + config.FilenameOrchestrionToolGo + ", returning error")
```
Comment (eliottness) [inline internal/pin/auto.go:61]:
```suggestion
			log.Trace().Err(err).Msg("Failed to stat " + config.FilenameOrchestrionToolGo + ", returning error")
```

File: internal/pin/auto.go [hunk 3]
```diff
@@ -21,60 +23,64 @@ import (
...
 		}
+		log.Trace().Err(err).Msg("Failed to detect required version of orchestrion from go.mod")
 	} else {
 		log.Trace().Msg("Skipping ensure.RequiredVersion because this is a development build")
 		_, err := os.Stat(config.FilenameOrchestrionToolGo)
 		if err == nil {
 			log.Trace().Msg("Found " + config.FilenameOrchestrionToolGo + " file, no automatic pinning required")
-			return
+			return nil
+		} else if !errors.Is(err, os.ErrNotExist) {
```
Comment (eliottness) [inline internal/pin/auto.go:60]: Same here with the `else`

File: internal/pin/auto_test.go [hunk 4]
```diff
@@ -25,7 +25,7 @@ func TestAutoPin(t *testing.T) {
 
 		tmp := scaffold(t, make(map[string]string))
 		require.NoError(t, os.Chdir(tmp))
-		AutoPinOrchestrion(context.Background())
+		AutoPinOrchestrion(context.Background(), os.Stdout, os.Stderr)
```
Comment (eliottness) [inline internal/pin/auto_test.go:28]: How about writing to `io.Discard` or optionnaly buffers to check there is actually something writen there

File: internal/pin/auto_test.go [hunk 5]
```diff
@@ -47,7 +47,7 @@ func TestAutoPin(t *testing.T) {
 
 		t.Setenv(envVarCheckedGoMod, "true")
 
-		AutoPinOrchestrion(context.Background())
+		AutoPinOrchestrion(context.Background(), os.Stdout, os.Stderr)
```
Comment (eliottness) [inline internal/pin/auto_test.go:50]: Same here

**Review by eliottness — CHANGES_REQUESTED** [review]

File: internal/pin/auto.go (hunk 1 above)
Comment (RomainMuller) [reply internal/pin/auto.go:54]: The diff context clearly shows otherwise?

**Review by eliottness — APPROVED** [review]
